# Generated by Django 6.0.3 on 2026-03-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patients",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=200)),
                ("age", models.IntegerField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "patients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CtImages",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image_path", models.CharField(max_length=500)),
                (
                    "gradcam_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("prediction_type", models.CharField(default="image", max_length=50)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ct_scans",
                        to="strocke_app.patients",
                    ),
                ),
            ],
            options={
                "db_table": "ct_images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bmi", models.FloatField()),
                ("smoking", models.CharField(max_length=50)),
                ("heartdisease", models.CharField(max_length=10)),
                ("diabetic", models.CharField(max_length=10)),
                ("kidneydisease", models.CharField(max_length=10)),
                ("diffwalking", models.CharField(max_length=10)),
                ("genhealth", models.CharField(max_length=50)),
                ("sleeptime", models.FloatField()),
                ("physicalhealth", models.IntegerField()),
                ("mentalhealth", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prediction_type",
                    models.CharField(default="clinical", max_length=50),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinical_records",
                        to="strocke_app.patients",
                    ),
                ),
            ],
            options={
                "db_table": "clinical_data",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Predictions",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("clinical_score", models.FloatField(blank=True, null=True)),
                ("image_score", models.FloatField(blank=True, null=True)),
                ("final_score", models.FloatField()),
                ("risk_level", models.CharField(max_length=20)),
                ("recommendation", models.TextField()),
                ("fusion_note", models.TextField(blank=True, null=True)),
                (
                    "overrides_triggered",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("explanation", models.TextField(blank=True, null=True)),
                (
                    "contributing_factors",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("model_version", models.CharField(default="v1.0", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("prediction_type", models.CharField(default="fusion", max_length=50)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to="strocke_app.patients",
                    ),
                ),
            ],
            options={
                "db_table": "predictions",
                "ordering": ["-created_at"],
            },
        ),
    ]
