# Generated by Django 4.2 on 2026-04-20 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strocke_app', '0002_alter_predictions_contributing_factors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllPatientsView',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('predictions_count', models.IntegerField()),
                ('last_risk', models.CharField(blank=True, max_length=20, null=True)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_patients_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AllPredictionsView',
            fields=[
                ('full_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('final_score', models.FloatField(blank=True, null=True)),
                ('contributing_factors', models.TextField(blank=True, null=True)),
                ('clinical_score', models.FloatField(blank=True, null=True)),
                ('image_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_predictions_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientsCountView',
            fields=[
                ('total_patients', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'patients_count_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PredictionsCountView',
            fields=[
                ('total_predictions', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'predictions_count_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='strocke_app.patients')),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
