# Generated by Django 4.2 on 2026-04-21 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strocke_app', '0003_allpatientsview_allpredictionsview_patientscountview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=20, unique=True)),
                ('file_path', models.CharField(max_length=500)),
                ('accuracy', models.FloatField()),
                ('cases_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('failed', 'Failed')], default='archived', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'model_versions',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmedCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('bmi', models.FloatField()),
                ('smoking', models.CharField(max_length=50)),
                ('heartdisease', models.CharField(max_length=10)),
                ('diabetic', models.CharField(max_length=10)),
                ('kidneydisease', models.CharField(max_length=10)),
                ('diffwalking', models.CharField(max_length=10)),
                ('genhealth', models.CharField(max_length=50)),
                ('sleeptime', models.FloatField()),
                ('physicalhealth', models.IntegerField()),
                ('mentalhealth', models.IntegerField()),
                ('system_prediction', models.CharField(max_length=20)),
                ('system_confidence', models.FloatField()),
                ('doctor_confirmed_label', models.CharField(max_length=20)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('used_in_training', models.BooleanField(default=False)),
                ('training_version', models.CharField(blank=True, max_length=20, null=True)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_cases', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_cases', to='strocke_app.patients')),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_cases', to='strocke_app.predictions')),
            ],
            options={
                'db_table': 'confirmed_cases',
                'ordering': ['-confirmed_at'],
            },
        ),
    ]
